server:
  port: 10082
spring:
  application.name: qctv1-ai-chat
  datasource:
    url: jdbc:mysql://localhost:3306/qctv1_ai?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: ${QCTV1_DB_MYSQL_USER}
    password: ${QCTV1_DB_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    dashscope:
      api-key: ${QCTV1_AI_API_KEY}
      image:
        retry:
          max-attempts: 5
          delay: 3000 # 每次重试间隔 3 秒
