spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            qctv1-iam:
              - uri: http://localhost:10083
    nacos:
      config:
        enabled: false
      discovery:
        enabled: false
